"""Package the finished research paper and email it via QQ Mail.

Collects: final manuscript (draft/), theory, numerical validation, analysis,
phase summaries, and the project brief. Zips everything and sends via smtplib
(himalaya times out on large attachments).
"""
import smtplib, os, sys, glob, subprocess
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from pathlib import Path
from datetime import datetime

PDIR = Path('/home/tez/research/projects/project-003-invariant-preserving_interacting_langevin')
ZIP_PATH = Path('/tmp/research-hub-paper.zip')
RECIPIENT = 'rqzhu-aide@qq.com'

# QQ Mail credentials from himalaya config
def get_qq_creds():
    """Extract QQ SMTP credentials from himalaya config.toml."""
    import re
    config = Path.home() / '.config/himalaya/config.toml'
    text = config.read_text()
    # Get login (numeric QQ)
    login_m = re.search(r'message\.send\.backend\.login\s*=\s*"([^"]+)"', text)
    if not login_m:
        login_m = re.search(r'\[accounts\.default\.message\.send\.backend\].*?login\s*=\s*"([^"]+)"', text, re.DOTALL)
    login = login_m.group(1) if login_m else ''
    # Get auth code
    auth_m = re.search(r'message\.send\.backend\.auth\.raw\s*=\s*"([^"]+)"', text)
    if not auth_m:
        auth_m = re.search(r'\[accounts\.default\.message\.send\.backend\].*?auth\.raw\s*=\s*"([^"]+)"', text, re.DOTALL)
    auth = auth_m.group(1) if auth_m else ''
    return login, auth

def find_manuscript():
    """Find the final assembled manuscript from phase 06."""
    draft = PDIR / 'draft'
    candidates = []
    # Look for assembled manuscript files
    for pattern in ['draft/manuscript*', 'draft/paper*', 'draft/*.md',
                    'draft/run/01/round-*/*.md', 'draft/final*']:
        for f in glob.glob(str(PDIR / pattern), recursive=True):
            if os.path.isfile(f):
                candidates.append(f)
    return candidates

def collect_files():
    """Collect all files to include in the zip."""
    files = []
    # Manuscript / draft outputs
    for subdir in ['draft', 'numerical']:
        d = PDIR / subdir
        if d.exists():
            for f in d.rglob('*'):
                if f.is_file() and not f.name.startswith('.'):
                    files.append(f)
    # Phase summaries
    summaries = PDIR / 'phase-summaries'
    if summaries.exists():
        for f in summaries.rglob('*'):
            if f.is_file():
                files.append(f)
    # Project brief
    setting = PDIR / 'setting.md'
    if setting.exists():
        files.append(setting)
    return files

def create_zip(files, zip_path):
    """Create a zip with relative paths."""
    import zipfile
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for f in files:
            arcname = str(f.relative_to(PDIR))
            zf.write(f, arcname)
    size_mb = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"Zip created: {zip_path} ({size_mb:.1f} MB, {len(files)} files)")
    return size_mb

def send_email(zip_path, size_mb):
    """Send the zip via QQ Mail using smtplib."""
    login, auth = get_qq_creds()
    if not login or not auth:
        print("ERROR: Could not get QQ credentials")
        return False
    
    msg = MIMEMultipart()
    msg['From'] = 'rqzhu-aide@qq.com'
    msg['To'] = RECIPIENT
    msg['Subject'] = f'Research Hub — Finished Paper ({datetime.now().strftime("%b %d, %Y")})'
    
    body = f"""Research Hub project-003 (Invariant-Preserving Interacting Langevin) — completed paper.

All 6 phases have run and been approved:
  01. Literature Review (including DMFT references)
  02. Method Development (FEP-NEA method selected)
  03. Theoretical Analysis
  04. Numerical Validation
  05. Scientific Interpretation
  06. Paper Writing

The attached zip contains:
  - Final manuscript and section drafts (draft/)
  - Numerical validation outputs (numerical/)
  - Phase summaries (phase-summaries/)
  - Project brief (setting.md)

Attachment: {os.path.basename(zip_path)} ({size_mb:.1f} MB)

Generated by Research Hub on {datetime.now().strftime('%Y-%m-%d %H:%M')}.
"""
    msg.attach(MIMEText(body, 'plain'))
    
    # Attach zip
    with open(zip_path, 'rb') as f:
        part = MIMEBase('application', 'zip')
        part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', 'attachment',
                       filename=os.path.basename(zip_path))
        msg.attach(part)
    
    print(f"Sending to {RECIPIENT} via smtp.qq.com...")
    with smtplib.SMTP_SSL('smtp.qq.com', 465, timeout=120) as server:
        server.login(login, auth)
        server.send_message(msg)
    print("✓ Email sent successfully")
    return True

def main():
    print("=== Research Hub Paper Packaging ===\n")
    
    # Step 1: Collect files
    print("1. Collecting files...")
    files = collect_files()
    manuscript = find_manuscript()
    print(f"   {len(files)} files found")
    print(f"   Manuscript candidates: {len(manuscript)}")
    for m in manuscript[:5]:
        print(f"     {Path(m).relative_to(PDIR)}")
    
    if not files:
        print("   ERROR: No files to package!")
        return False
    
    # Step 2: Create zip
    print("\n2. Creating zip...")
    size_mb = create_zip(files, ZIP_PATH)
    
    # Step 3: Send email
    print("\n3. Sending email...")
    try:
        return send_email(ZIP_PATH, size_mb)
    except Exception as e:
        print(f"   ERROR: {e}")
        return False

if __name__ == '__main__':
    success = main()
    sys.exit(0 if success else 1)
